[package]
name = "simple-stream"
version = "0.9.6"
authors = ["Nathan Sizemore <nathanrsizemore@gmail.com>"]
description = "Provides various building blocks, abstractions, and types for streams."
readme = "README.md"
keywords = ["socket", "stream", "non-blocking", "websocket", "ssl"]
license = "MPL-2.0"
repository = "https://github.com/nathansizemore/simple-stream"
documentation = "https://nathansizemore.github.io/simple-stream/simple_stream/index.html"

[lib]
name = "simple_stream"

[dependencies]
log = "^0.3.5"
libc = "^0.2.10"
errno = "^0.1.6"
openssl = "^0.7.10"
bitflags = "^0.6.0"
