[package]
name = "simple-stream"
version = "0.2.0"
authors = ["Nathan Sizemore <nathanrsizemore@gmail.com>"]
description = "Simple messaging protocol built on non-blocking TcpStream"
repository = "https://github.com/nathansizemore/simple-stream"
readme = "README.md"
keywords = ["tcp", "non", "blocking", "socket"]
license = "MPL 2.0"

[dependencies]
errno = "*"
libc = "*"
