[package]
name = "simple-stream"
version = "0.1.0"
authors = ["Nathan Sizemore <nathanrsizemore@gmail.com>"]
description = "Stream crate with simple framing protocol built in"
readme = "README.md"
keywords = ["tcp", "non", "blocking", "socket", "stream"]
license = "MPL-2.0"
repository = "https://github.com/nathansizemore/simple-stream"
homepage = "https://github.com/nathansizemore/simple-stream"
documentation = "https://nathansizemore.github.io/simple-stream/simple_stream/index.html"

[dependencies]
log = "*"
errno = "*"
libc = "*"
openssl = "*"
